projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        url: http://localhost:8099
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
