
# ~/.tmuxinator/users-lib.yml

name: users
root: ~/Sources/users

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specitifes (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t users-lib
parameters:
    path_lib: &cd_to_lib 'cd users-lib'
    path_ui:  &cd_to_ui  'cd users-ui'
    path_api: &cd_to_api 'cd users-api'
windows:
  - users-api:
      layout: 'main-horizontal'
      panes:
        - api_docker:
            - cd users-api/docker
            - docker-compose up
        - api_prisma_deploy:
            - cd users-api
            - sleep 15
            - prisma deploy -w
        - api_prisma_playground:
            - cd users-api
            - sleep 15
            - prisma playground
        - api_prisma_api:
            - cd users-api
            - sleep 15
            - docker exec -ti usersapi_back-server_1 /bin/sh
            - cd /app
            - node src/index.js
